spring.application.name=pedidos-kafka
server.port=${SERVER_PORT:8080}
pedidos.kafka.topic=${PEDIDOS_KAFKA_TOPIC:pedidos-eventos}
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
kafka.plain.acks=${KAFKA_PLAIN_ACKS:all}
kafka.plain.retries=${KAFKA_PLAIN_RETRIES:3}
kafka.plain.delivery.timeout.ms=${KAFKA_PLAIN_DELIVERY_TIMEOUT_MS:120000}
kafka.plain.request.timeout.ms=${KAFKA_PLAIN_REQUEST_TIMEOUT_MS:30000}
kafka.plain.max.block.ms=${KAFKA_PLAIN_MAX_BLOCK_MS:60000}
kafka.ssl.bootstrap.servers=${KAFKA_SSL_BOOTSTRAP_SERVERS:localhost:9093}
kafka.ssl.schema.registry.url=${KAFKA_SSL_SCHEMA_REGISTRY_URL:http://localhost:8081}
kafka.ssl.acks=${KAFKA_SSL_ACKS:all}
kafka.ssl.retries=${KAFKA_SSL_RETRIES:3}
kafka.ssl.delivery.timeout.ms=${KAFKA_SSL_DELIVERY_TIMEOUT_MS:120000}
kafka.ssl.request.timeout.ms=${KAFKA_SSL_REQUEST_TIMEOUT_MS:30000}
kafka.ssl.max.block.ms=${KAFKA_SSL_MAX_BLOCK_MS:60000}
kafka.ssl.truststore.location=${KAFKA_SSL_TRUSTSTORE_LOCATION:}
kafka.ssl.truststore.password=${KAFKA_SSL_TRUSTSTORE_PASSWORD:}
kafka.ssl.endpoint.identification.algorithm=${KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM:https}
